### PR TITLE
Only updates morphdom@2.1.0

### PR DESCRIPTION
**Pull request by kristoferjoseph**
because ❤️

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
fixes #41

**Comment by arturi** [comment]
Very excited about this!

**Comment by yoshuawuyts** [comment]
amaze :tada: :tada: :tada:

**Comment by ajoslin** [comment]
Such major version. 💯

**Comment by yoshuawuyts** [comment]
Published as `v1.3.0` :tada: :tada:

**Comment by yoshuawuyts** [comment]
Adding a reference to the patch this superseded https://github.com/maxogden/yo-yo/pull/44 :sparkles: (makes it easier to find when referencing issues haha)

**Pull request merged**
