### PR TITLE
Pin morphdom to 2.1

### PR DESCRIPTION
**Pull request by aknuds1**
Pin morphdom to 2.1.x as 2.2 introduces regressions

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
LGTM, we should release this ASAP

**Comment by yoshuawuyts** [comment]
`v1.3.2` :tada:

**Comment by kristoferjoseph** [comment]
Ah crap. What regressions?

**Comment by yoshuawuyts** [comment]
we've had 2 reports already and one that might be an issue, 1 was fixed
already but the other's still there - reverting just to make sure :/

**Comment by aknuds1** [comment]
@kristoferjoseph The regression I was seeing was that `selectedIndex` is no longer set on `select` elements. I tried setting this both via `selected` attribute on `option` elements and `selectedIndex` on the `select` itself.

I haven't found out why the regression is happening, but going back to morphdom 2.1 helps.

**Comment by kristoferjoseph** [comment]
OK. Thanks for the info. Will take a look once I find time.

**Pull request merged**
