### PR TITLE
copy values for form elements

### PR DESCRIPTION
**Pull request by ghost**
If a user is typing into a `<textarea>`, `<input>`, or chooses an option in a `<select>` box, their input is erased when an update occurs. This patch copies the previous element value if there is no attribute value defined for the next version, which is what virtual-dom and react do.

### CODE REVIEW

**Comment by nichoth** [comment]
nice

**Comment by allouis** [comment]
@substack should this change happen in `morphdom` instead?

**Comment by shama** [comment]
LGTM!

@patrick-steele-idem Do you think this logic should belong in `morphdom` or in the implementation here?

**Comment by SilentCicero** [comment]
@substack great find ! I would have definitely run into that. @shama I think this logic could go into yoyo. It's really necessary. But if morphdom provides support, I'm not against it.

**Comment by patrick-steele-idem** [comment]
The solution provided by @substack is the recommended usage. While you typically want to preserve input values, that may not _always_ be the case so we intentionally leave it up to users of `morphdom` to decide. If `morphdom` were to ever offer the ability to preserve input values it would be done via an opt-in option and it would be done in much the same way. For now I recommend going forward with using the provided hooks to preserve input values.

**Comment by SilentCicero** [comment]
@patrick-steele-idem great work on `morphdom` love it =D

**Comment by shama** [comment]
@patrick-steele-idem Thanks!

**Pull request merged**
